### ISSUE TITLE
Getting errors after update?

### ISSUE THREAD

**Issue by m0ngr31** [gf3/moment-range#76]
After updating to 1.1.0, we are getting this error when we are running our tests.

```
ReferenceError: Can't find variable: require
at /myApp/bower_components/moment-range/lib/moment-range.js:5
```

Any suggestions?

**Comment by fomubik** [comment]
Got the same error after update. It broke my app. I must revert to v 1.0.9 to make app work again. I guess something is wrong with the way require is called here https://github.com/gf3/moment-range/commit/4c492ddc2f870614e62fd9c8900681f1f5dd67ce#diff-8

**Comment by m0ngr31** [comment]
Yeah, I ended up hardcoding 1.0.9 into bower.json to fix it.

**Comment by gf3** [comment]
@m0ngr31 @fomubik hmm okay, i'll look into it. i assume you're using it in the browser?

**Comment by m0ngr31** [comment]
Testing was using PhantomJS.

**Comment by gf3** [comment]
should be fixed in [1.1.1](https://github.com/gf3/moment-range/releases/tag/1.1.1) sorry about that!

**Comment by fomubik** [comment]
@gf3 Yes, i use it as a bower dependency.

**Comment by m0ngr31** [comment]
Still not working for me. Getting the same error as before when running `grunt test`

**Comment by gf3** [comment]
@fomubik @m0ngr31 ok, reverted from browserify back to UMD. should be fixed in [1.1.2](https://github.com/gf3/moment-range/releases/tag/1.1.2)
